### ISSUE TITLE
Not able to add domain in blackest

### ISSUE THREAD

**Issue by Mukesh-Chaudhari** [syncloud/pihole#2]
Pi-hole is Installed on beagle one black with Syncloud.

It's working alright but I want to improve ad-blocking and it's not allowing to add domains in blacklist.

Also setting appear little different then Raspberry-Pi setup.

Can you please help me to improve my domain blacklist so ad-blocking performance can improve.

Thanks

**Comment by Mukesh-Chaudhari** [comment]
Hi anybody there to help me

**Comment by cyberb** [comment]
I think you can actually add a domain to the blacklist it is just a UI issue.
Try 
1. Add a domain to blacklist
2. Refresh page

**Comment by Mukesh-Chaudhari** [comment]
I already tried that but the total  number of blocked domains not increased and also it's not blocking any added dominos.

Thank you for your help.

I moved on and installed clean version on Debian for Pi-hole 

Thank you once again and keep it up.
